function:
  handler: src/starry_report_data_csv.handler
  name: ${self:service}-data-csv-${self:provider.stage}
  description: omni email starry data report csv generation into S3 bucket  - ${self:provider.stage}
  memorySize: 2048
  timeout: 600
  package:
    include:
    - /src/starry_report_data_csv.py
    exclude:
    - config/**
    - psycopg2/**
    - pandas/**
    - numpy/**
    - pytz/**
    - numpy-1.20.1.dist-info/**
    - numpy.libs/**
    - pandas-1.2.3.dist-info/**
    - pytz-2021.1.dist-info/**
    - six-1.15.0.dist-info/**
    - six.py
    - templates/**
  events:
    - eventBridge:
       schedule: cron(00 13 * * ? *)

  environment:
    DBNAME: ${ssm:/omni-dw/prod/db/name}
    USER: ${ssm:/omni-dw/${self:provider.stage}/db/user~true}
    CLUSTERID: ${ssm:/omni-dw/prod/cluster/identifier}